# 项目相关配置
ringtone:
  # 名称
  name: ringtone
  # 版本
  version: 0.0.10
  # 版权年份
  copyrightYear: 2019
  # 文件上传路径
  profile: C:/profile
  #文件访问地址
  profile-url: http://120.27.226.14/
#  profile-url: http://127.0.0.1/
  # 获取ip地址开关
  addressEnabled: true

# tomcate 基本配置
server:
  # tomcate 端口号
  port: 80
  servlet:
    # tomcat 访问跟路径
    context-path: /
    session:
      timeout: 7200s
  tomcat:
    #tomcat 工作线程的最大数量
    max-threads: 200
    # tomcat 辅助线程的最小数量
    min-spare-threads: 10
    # 服务器在任何给定时间接受和处理的最大连接数
    max-connections: 1000


# 日志配置
logging:
  level:
    com.hrtxn.ringtone: debug

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.hrtxn.ringtone.project/**
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
#    configuration:
     # 驼峰命名规范
#    map-underscore-to-camel-case: true

# spring 配置
spring:
  # 选择环境
  profiles:
    active: dev
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    # 禁用缓存
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  #（虚拟路径）
#  mvc:
#    static-path-pattern: images/**
#  resources:
#    #（图片所在的位置）
#    static-locations: file:D:/profile
# 是否开启springboot 调试模式
#debug: true

# shiro
shiro:
  session:
    # Session超时时间（默认30分钟）
    expireTime: 120
  cookie:
    # 设置Cookie的过期时间，天为单位
    maxAge: 120

http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 10000
  connectionRequestTimeout : 5000
  socketTimeout: 10000
  staleConnectionCheckEnabled: true